cookie:
  expiry_days: 15
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    Stalyn Guerrero:
      email: none
      name: Stalyn Guerrero
      password: $2b$12$KLp2C/5fuftc4oOD7tRBlOnEtJBeryuMQFG1cGyvjNyeFktmH03ti
      roles:
      - admin
    administrador:
      email: none
      name: Administrador
      password: a12345
      roles:
      - admin
    usuario:
      email: none
      name: Usuario
      password: u12345
      roles:
      - user
preauthorized:
  emails: []
