cookie:
  expiry_days: 30
  key: clave_segura
  name: reemplazos_cookie
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrador
      password: $2b$12$s2VSS9VUSN4YyB72vSpzmusvlOGV0mqZrQUvQN3u.Hc7TYUKVeUdq
      roles:
      - admin
    usuario1:
      email: guerrerostalyn@gmail.com
      name: 'Stalyn Guerrero '
      password: $2b$12$s2VSS9VUSN4YyB72vSpzmusvlOGV0mqZrQUvQN3u.Hc7TYUKVeUdq
      roles:
      - user
preauthorized:
  emails: []
