cookie:
  expiry_days: 30
  key: clave_segura
  name: reemplazos_cookie
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrador
      password: "u12345"  # Texto plano
      roles:
      - admin
    usuario1:
      email: guerrerostalyn@gmail.com
      name: 'Stalyn Guerrero'
      password: "u12345"  # Texto plano
      roles:
      - user
preauthorized:
  emails: []
