cookie:
  expiry_days: 30
  key: clave_segura
  name: reemplazos_cookie
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrador
      password: $2b$12$s2VSS9VUSN4YyB72vSpzmusvlOGV0mqZrQUvQN3u.Hc7TYUKVeUdq
      roles:
      - admin
    monica.suarez:
      email: monica.suarez@idt.gov.co
      name: Mónica Gimena Suarez Forero
      password: monica.1234
      roles:
      - user
    katheryn.cabrera:
      email: katheryn.cabrera@idt.gov.co
      name: Katheryn Mayerly Cabrera Roa
      password: Kathe.1234
      roles:
      - user
    cindy.gonzalez:
      email: cindy.gonzalez@idt.gov.co
      name: Cindy Alejandra González Duque
      password: Cindy.1234
      roles:
      - user
    andres.gutierrez:
      email: andres.gutierrez@idt.gov.co
      name: Carlos Andrés Gutiérrez Carrero
      password: Andres.1234
      roles:
      - user
    diana.quinones:
      email: diana.quinones@idt.gov.co
      name: Diana Liseth Quiñones Montaño
      password: Diana.1234
      roles:
      - user
    diana.suarez:
      email: diana.suarez@idt.gov.co
      name: Diana Estefanía Suarez Vargas
      password: DianaS.1234
      roles:
      - user
    jose.ramirez:
      email: jose.ramirez@idt.gov.co
      name: José Yesid Ramírez Ruíz
      password: Jose.1234
      roles:
      - user
    alizon.pinilla:
      email: alizon.pinilla@idt.gov.co
      name: Alizon Michell Pinilla Pabón
      password: Alizon.1234
      roles:
      - user
    claudia.martinez:
      email: claudia.martinez@idt.gov.co
      name: Claudia Paola Martínez Rodríguez
      password: Claudia.1234
      roles:
      - user
    nini.camacho:
      email: nini.camacho@idt.gov.co
      name: Nini Johanna Camacho Traslaviña
      password: Nini.1234
      roles:
      - user
    andres.quintero:
      email: andres.quintero@idt.gov.co
      name: Andrés Fernando Quintero Atará
      password: AndresQ.1234
      roles:
      - user
preauthorized:
  emails: []
