cookie:
  expiry_days: 30
  key: clave_segura
  name: reemplazos_cookie
credentials:
  usernames:
    admin:
      email: admin@example.com
      name: Administrador
      password: $2b$12$s2VSS9VUSN4YyB72vSpzmusvlOGV0mqZrQUvQN3u.Hc7TYUKVeUdq
      roles:
      - admin
    monica.suarez:
      email: monica.suarez@idt.gov.co
      name: Mónica Gimena Suarez Forero
      password: $2b$12$8QZzLkqW9nY8Yb6JtKqjUO3vR8mXwN2pT7sV1cGpL9hM3yAeE6Ku
      roles:
      - user
    katheryn.cabrera:
      email: katheryn.cabrera@idt.gov.co
      name: Katheryn Mayerly Cabrera Roa
      password: $2b$12$LpPxMwRrT7sV3cGpL9hM3yAeE6Ku8QZzLkqW9nY8Yb6JtKqjUO
      roles:
      - user
    cindy.gonzalez:
      email: cindy.gonzalez@idt.gov.co
      name: Cindy Alejandra González Duque
      password: $2b$12$3cGpL9hM3yAeE6Ku8QZzLkqW9nY8Yb6JtKqjUO3vR8mXwN2pT7
      roles:
      - user
    andres.gutierrez:
      email: andres.gutierrez@idt.gov.co
      name: Carlos Andrés Gutiérrez Carrero
      password: $2b$12$9hM3yAeE6Ku8QZzLkqW9nY8Yb6JtKqjUO3vR8mXwN2pT7sV1cGpL
      roles:
      - user
    diana.quinones:
      email: diana.quinones@idt.gov.co
      name: Diana Liseth Quiñones Montaño
      password: $2b$12$yAeE6Ku8QZzLkqW9nY8Yb6JtKqjUO3vR8mXwN2pT7sV1cGpL9hM3
      roles:
      - user
    diana.suarez:
      email: diana.suarez@idt.gov.co
      name: Diana Estefanía Suarez Vargas
      password: $2b$12$E6Ku8QZzLkqW9nY8Yb6JtKqjUO3vR8mXwN2pT7sV1cGpL9hM3yAe
      roles:
      - user
    jose.ramirez:
      email: jose.ramirez@idt.gov.co
      name: José Yesid Ramírez Ruíz
      password: $2b$12$Ku8QZzLkqW9nY8Yb6JtKqjUO3vR8mXwN2pT7sV1cGpL9hM3yAeE6
      roles:
      - user
    alizon.pinilla:
      email: alizon.pinilla@idt.gov.co
      name: Alizon Michell Pinilla Pabón
      password: $2b$12$u8QZzLkqW9nY8Yb6JtKqjUO3vR8mXwN2pT7sV1cGpL9hM3yAeE6K
      roles:
      - user
    claudia.martinez:
      email: claudia.martinez@idt.gov.co
      name: Claudia Paola Martínez Rodríguez
      password: $2b$12$8QZzLkqW9nY8Yb6JtKqjUO3vR8mXwN2pT7sV1cGpL9hM3yAeE6Ku
      roles:
      - user
    nini.camacho:
      email: nini.camacho@idt.gov.co
      name: Nini Johanna Camacho Traslaviña
      password: $2b$12$LkqW9nY8Yb6JtKqjUO3vR8mXwN2pT7sV1cGpL9hM3yAeE6Ku8QZ
      roles:
      - user
    andres.quintero:
      email: andres.quintero@idt.gov.co
      name: Andrés Fernando Quintero Atará
      password: $2b$12$qW9nY8Yb6JtKqjUO3vR8mXwN2pT7sV1cGpL9hM3yAeE6Ku8QZzL
      roles:
      - user
preauthorized:
  emails: []
